spring.application.name=api-gateway
server.port=8080

##----------routing for book-service-------------
#spring.cloud.gateway.routes[0].id=book-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/book/**
##
###----------routing for order-service------------
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

#default zone
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

#enable dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#to convert URL to lowercase
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#url to be called
#http://localhost:8888/USER_SERVICE/save --> :8081/user/save