spring.application.name=StudentManagement
spring.datasource.url= jdbc:postgresql://localhost:5433/StudentManagementSystem
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# actuator
management.endpoints.web.exposure.include=*

# cache
spring.cache.type=simple
server.port=8080