spring.application.name=api_gateway
server.port= 8888

#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

#spring.cloud.gateway.routes[1].id=product-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**

#spring.cloud.gateway.routes[2].id=payment-service
#spring.cloud.gateway.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.routes[2].predicates[0]=Path=/payment/**

#default zone
eureka.client.serviceUrl.defaultZone=http://localhost:8761/registry/eureka

#enable dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#to convert URL to lowercase
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#url to be called
#http://localhost:8888/USER_SERVICE/save --> :8081/user/save
