spring.application.name=config-server

server.servlet.context-path=/config

server.port=9999

spring.cloud.config.server.git.uri=https://github.com/Mandira001/cloud-config.git

#default path
#http://localhost::9999/config

